# Generated by Django 4.0 on 2021-12-26 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-time_create'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Пости'},
        ),
    ]
