# Generated by Django 4.0 on 2021-12-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_category_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(upload_to='blog_django/media/photos/%Y/%m/%d', verbose_name='Фото'),
        ),
    ]
