# Generated by Django 4.0 on 2021-12-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_post_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Фото'),
        ),
    ]
